version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://playground:password@postgres:5432/playgrounds
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-jwt-secret-key
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=playground
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=playgrounds
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  playground-runtime:
    build:
      context: .
      dockerfile: Dockerfile.playground
    ports:
      - "1337:1337"
      - "1338:1338"
    volumes:
      - playground_workspaces:/workspace
    privileged: true  # Required for Docker-in-Docker

volumes:
  postgres_data:
  redis_data:
  playground_workspaces: